/**
 * Australian recreational fishing species list — Queensland-focused, national coverage.
 * Common names as used by Australian anglers. Sorted alphabetically within groups.
 * Sources: QLD DPI Fish Species Guide, NSW DPI, AFMA, community fishing guides.
 */
export const SPECIES_LIST = [

  // ── Estuary & Inshore ────────────────────────────────────────────────────
  'Barramundi',
  'Bream (Black)',
  'Bream (Pikey)',
  'Bream (Tarwhine)',
  'Bream (Yellowfin)',
  'Cobia',
  'Dart',
  'Dart (Swallowtail)',
  'Estuary Cod',
  'Estuary Perch',
  'Flathead (Bar-tailed)',
  'Flathead (Dusky)',
  'Flathead (Northern)',
  'Flathead (Rock)',
  'Flathead (Tiger)',
  'Flounder',
  'Garfish',
  'Garfish (River)',
  'Groper (Blue)',
  'Grunter (Khaki)',
  'Grunter (Sooty)',
  'Grunter (Javelin)',
  'Grunter Bream',
  'Hairtail',
  'Leatherjacket',
  'Leatherjacket (Fan-bellied)',
  'Leatherjacket (Six-spined)',
  'Luderick',
  'Mangrove Jack',
  'Mullet (Sea)',
  'Mullet (Yellow-eye)',
  'Mullet (Flathead)',
  'Mulloway',
  'Permit',
  'Queenfish',
  'Queenfish (Needlescaled)',
  'Salmon (Australian)',
  'Snapper',
  'Tarpon',
  'Tailor',
  'Threadfin Salmon (Blue)',
  'Threadfin Salmon (King)',
  'Trevally (Brassie)',
  'Trevally (Diamond)',
  'Trevally (Bigeye)',
  'Trevally (Giant)',
  'Trevally (Golden)',
  'Trevally (Silver)',
  'Trevally (Skipjack)',
  'Trevally (Turrum)',
  'Tuskfish (Blackspot)',
  'Tuskfish (Blue)',
  'Tuskfish (Venus)',
  'Whiting (King George)',
  'Whiting (Sand)',
  'Whiting (School)',
  'Whiting (Summer)',
  'Whiting (Trumpeter)',

  // ── Reef & Offshore ──────────────────────────────────────────────────────
  'Amberjack',
  'Barracuda (Great)',
  'Barramundi Cod',
  'Coral Trout (Bar-cheeked)',
  'Coral Trout (Common)',
  'Coral Trout (Leopard)',
  'Coral Trout (Passionfruit)',
  'Crimson Snapper',
  'Drummer (Black)',
  'Drummer (Rock)',
  'Emperor (Grass)',
  'Emperor (Longface)',
  'Emperor (Redthroat)',
  'Emperor (Spangled)',
  'Emperor (Sweetlip)',
  'Emperor (Yellowlip)',
  'Fingermark',
  'Goldband Snapper',
  'Grouper (Flowery)',
  'Grouper (Honeycomb)',
  'Grouper (Squaretail)',
  'Hussar',
  'Maori Wrasse',
  'Nannygai (Large Mouth)',
  'Nannygai (Small Mouth)',
  'Nannygai (Saddletail)',
  'Parrotfish',
  'Pearl Perch',
  'Red Emperor',
  'Samson Fish',
  'Scarlet Seaperch',
  'Snapper (Crimson)',
  'Snapper (Moses)',
  'Stripey Seaperch',
  'Surgeonfish',
  'Sweetlip (Painted)',
  'Sweetlip (Grass)',
  'Triggerfish',
  'Wrasse (Slingjaw)',

  // ── Pelagic & Game Fish ──────────────────────────────────────────────────
  'Cobia',
  'Dolphinfish (Mahi Mahi)',
  'Mackerel (School)',
  'Mackerel (Shark)',
  'Mackerel (Spotted)',
  'Mackerel (Spanish)',
  'Marlin (Black)',
  'Marlin (Blue)',
  'Marlin (Striped)',
  'Sailfish',
  'Spearfish',
  'Tuna (Bigeye)',
  'Tuna (Dogtooth)',
  'Tuna (Longtail)',
  'Tuna (Mackerel)',
  'Tuna (Skipjack)',
  'Tuna (Southern Bluefin)',
  'Tuna (Yellowfin)',
  'Wahoo',
  'Yellowtail Kingfish',

  // ── Freshwater ───────────────────────────────────────────────────────────
  'Australian Bass',
  'Carp',
  'Catfish (Eel-tailed)',
  'Catfish (Fork-tailed)',
  'Cod (Mary River)',
  'Cod (Murray)',
  'Cod (Trout)',
  'Galaxias',
  'Jungle Perch',
  'Lungfish (Queensland)',
  'Perch (Golden / Yellowbelly)',
  'Perch (Redfin)',
  'Perch (Silver)',
  'Perch (Spangled)',
  'Saratoga (Northern)',
  'Saratoga (Southern)',
  'Sleepy Cod',
  'Tilapia (Pest species)',
  'Trout (Brook)',
  'Trout (Brown)',
  'Trout (Rainbow)',

  // ── Sharks ───────────────────────────────────────────────────────────────
  'Shark (Blue)',
  'Shark (Bronze Whaler)',
  'Shark (Bull)',
  'Shark (Gummy)',
  'Shark (Hammerhead)',
  'Shark (Mako)',
  'Shark (Nurse)',
  'Shark (Port Jackson)',
  'Shark (School)',
  'Shark (Thresher)',
  'Shark (Tiger)',
  'Shark (Whaler)',
  'Shark (Wobbegong)',

  // ── Rays ─────────────────────────────────────────────────────────────────
  'Eagle Ray',
  'Fiddler Ray',
  'Guitarfish',
  'Sawfish',
  'Shovelnose Ray',
  'Stingray',
  'Stingray (Cowtail)',

  // ── Cephalopods & Crustaceans ─────────────────────────────────────────────
  'Crab (Blue Swimmer)',
  'Crab (Mud)',
  'Crab (Sand)',
  'Crayfish (Freshwater / Yabby)',
  'Crayfish (Redclaw)',
  'Crayfish (Spiny)',
  'Prawn (Banana)',
  'Prawn (Tiger)',
  'Squid (Arrow)',
  'Squid (Southern Calamari)',

  // ── Other ─────────────────────────────────────────────────────────────────
  'Blowfish / Puffer',
  'Catfish (Saltwater)',
  'Cockney Bream',
  'Eel (Short-finned)',
  'Eel (Long-finned)',
  'Gudgeon',
  'Hardyhead',
  'Morwong',
  'Morwong (Jackass)',
  'Morwong (Red)',
  'Porcupinefish',
  'Soapfish',
  'Stonefish',
  'Unknown / Not Identified',

] as const;

export type Species = (typeof SPECIES_LIST)[number];
